routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/applicationForm/{id}', 'ApplicantController@apply');
Route::get('/viewJob/{id}', 'CareerController@viewJob');
Route::get('/viewAllJobs', function () {
    return view('viewAllJobs');
});
Route::get('/', function () {
  $message = "Welcome to OnSets!";
    return view('welcome', compact('message'));
});
Route::resource('/queries', 'QueryController');
Route::resource('/subcribeEmails', 'SubscribeController');
Route::get('/differnt/{status}', 'QueryController@DifferentQuery');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/ourinfo', 'HomeController@ourinfo');
Route::get('/viewAllStories', 'HomeController@viewAllStories');
Route::post('/ourinfoAdd', 'HomeController@ourinfoAdd');
Route::post('/ourinfoUpdate/{id}', 'HomeController@ourinfoUpdate');
Route::get('/viewApplicants/{id}', 'ApplicantController@viewApplicants');
Route::resource('/addresses', 'AddressController');
Route::resource('/products', 'ProductController');
Route::resource('/projects', 'ProjectController');
Route::resource('/careers', 'CareerController');
Route::resource('/stories', 'StoryController');
Route::resource('/roles', 'RoleController');
Route::resource('/applicants', 'ApplicantController');
Route::resource('/users', 'userController');
Route::resource('/contacts', 'ContactController');


Route::post('/usersContact', 'userController@infoAddContact');
Route::post('/usersAddress', 'userController@infoAddAddress');
Route::post('/usersContactD/{id}/{contact}', 'userController@infoDeleteContact');
Route::post('/usersAddressD/{id}/{address}', 'userController@infoDeleteAddress');
Route::get('/userContact/{id}', 'userController@AddContactView');
Route::get('/userAddress/{id}', 'userController@AddAddressView');
Route::get('/ContactEdit/{id}/{contact}', 'userController@EditContactView');
Route::get('/AddressEdit/{id}/{address}', 'userController@EditAddressView');
Route::post('/UpdateContact/{id}', 'userController@UpdateContact');
Route::post('/updateAddress/{id}', 'userController@updateAddress');


Route::resource('/media', 'MediaController');
Route::resource('/sliders', 'SliderController');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //

    protected $table = 'projects';
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Redirect;
use \App\Project;
use File;
use Intervention\Image\ImageManagerStatic as Image;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


     public function __construct()
     {
         $this->middleware('auth');
     }

    public function index()
    {
        return view('project.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('project.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $project =new Project;
      $project->uploaderID    =Auth::id();
      $project->title         =$request->name;
      $project->URL           =$request->link;
      $project->projectOwner  =$request->projectOwner;
      $project->status        =$request->status;
      $project->collaborationDate=$request->collabrationDate;
      $description     =$request->editor1;
      $comments =$request->comments;
      $destinationImages='project/images';
      $allowedImagefileExtension=['jpg','png','jpeg'];
      $destinationVideo='project/videos';
      $allowedVideofileExtension=['mp4','flv','m4p','mpg','mpeg','webm','mov'];

      $projectDescriptionFile = time();
      $projectDescriptionUrl = "/project/".$projectDescriptionFile.".txt";
      Storage::put($projectDescriptionUrl, $description);
      $project->description= $projectDescriptionFile.".txt";

      $projectCommentFile = time();
      $projectCommentUrl = "/project-comments/".$projectCommentFile.".txt";
      Storage::put($projectCommentUrl, $comments);
      $project->projectOwnerComment	=  $projectCommentFile.".txt";

      if($request->hasFile('image')){
        $file=Input::file("image");
        $extension = $file->getClientOriginalExtension();
        $checkImage=in_array($extension,$allowedImagefileExtension);
        $checkVideo=in_array($extension,$allowedVideofileExtension);
        $filename = time() . '-' .$file->getClientOriginalName();
        if($checkImage){
          $image = Image::make($file);
          $image->resize(500, 500);
          $url = $destinationImages.'/'.$filename;

          if (!file_exists($destinationImages)) {
            mkdir($destinationImages, 666, true);
          }

          $image->save($url);
          $project->projectImage = $filename;
        }
        elseif($checkVideo){
          $file->move($destinationVideo,$filename);
          $project->$projectVideo = $filename;
        }
        else{
          $message = "Only JPEG, JPG, PNG formats allowed for images!";
          return view("project.create", compact('message', 'title', 'status', 'url', 'description'));
        }
        $project->save();
        $color = "success";
      }
      if($request->hasFile('images')){
        $files=Input::file("images");
        foreach ($files as $key => $file) {
          $extension = $file->getClientOriginalExtension();
          $checkImage=in_array($extension,$allowedImagefileExtension);
          $filename = time() . '-' .$file->getClientOriginalName();
          if($checkImage){
            $image = Image::make($file);
            $image->resize(500, 500);
            $media = new \App\Media;
            $url = $destinationImages.'/'.$filename;

            if (!file_exists($destinationImages)) {
              mkdir($destinationImages, 666, true);
            }
            
            $image->save($url);
            $media->name = $filename;
            $media->type = "image";
            $media->for = "project";
            $media->forId = $project->id;
            $media->status = "Active";
            $media->save();
          }
          else{
            $message = "Only JPEG, JPG, PNG formats allowed for images!";
            $color = "danger";
            return view("project.create", compact('message', 'title', 'status', 'url', 'description', 'color'));
          }
        }
      }
      if($request->hasFile('videos')){
        $files=Input::file("videos");
        foreach ($files as $key => $file) {
          $extension = $file->getClientOriginalExtension();
          $checkVideo=in_array($extension,$allowedVideofileExtension);
          $filename = time() . '-' .$file->getClientOriginalName();
          if($checkVideo){
            $media = new \App\Media;
            $file->move($destinationVideo,$filename);
            $media->name = $filename;
            $media->type = "video";
            $media->for = "project";
            $media->forId = $project->id;
            $media->status = "Active";
            $media->save();
          }
          else{
            $message = "Only MP4, M4P, MOV, WEBM, MPEG, FLV formats allowed for videos!";
            $color = "danger";
            return view("project.create", compact('message', 'title', 'status', 'url', 'description', 'color'));
          }
        }
      }

      $message = "Project Saved";
      $color='success';
      return view('project.index', compact('message','color'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('project.show', compact('id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      return view('project.edit', compact('id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $project = Project::find($id);
      $project->uploaderID    = Auth::id();
      $project->title         =$request->name;
      $project->URL           =$request->link;
      $project->projectOwner  =$request->projectOwner;
      $project->status        =$request->status;
      $description     =$request->editor1;
      $comments =$request->comments;
      $destinationImages='project/images';
      $allowedImagefileExtension=['jpg','png','jpeg'];
      $destinationVideo='project/videos';
      $allowedVideofileExtension=['mp4','flv','m4p','mpg','mpeg','webm','mov'];

      if(!empty($request->hasFile('image'))){
        $file=Input::file("image");
        $extension = $file->getClientOriginalExtension();
        $checkImage=in_array($extension,$allowedImagefileExtension);
        $checkVideo=in_array($extension,$allowedVideofileExtension);
        $filename = time() . '-' .$file->getClientOriginalName();
        if($checkImage){
          if(!empty($project->projectImage)){
            $path = 'project/images/'.$project->projectImage;
            File::delete($path);
            $project->projectImage = null;
          }
          elseif(!empty($project->projectVideo)){
            $path = 'project/videos/'.$project->projectVideo;
            File::delete($path);
            $project->projectVideo = null;
          }
          $image = Image::make($file);
          $image->resize(500, 500);
          $url = $destinationImages.'/'.$filename;
          $image->save($url);
          $project->projectImage = $filename;
        }
        elseif(!empty($project->projectImage)){
          if(!empty($project->projectImage)){
            $path = 'project/images/'.$project->projectImage;
            File::delete($path);
            $project->projectImage = null;
          }
          elseif(!empty($project->projectVideo)){
            $path = 'project/videos/'.$project->projectVideo;
            File::delete($path);
            $project->projectVideo = null;
          }
          $file->move($destinationVideo,$filename);
          $project->projectVideo = $filename;
        }
        else{
          $message = "Only JPEG, JPG, PNG formats allowed for images!";
          $color = "danger";
          return view("project.create", compact('message', 'title', 'status', 'url', 'description', 'danger'));
        }
      }
      if(!empty($request->collabrationDate)){
        $project->collaborationDate=$request->collabrationDate;
      }
      else{
        $project->collaborationDate=$project->collaborationDate;
      }

      if($request->hasFile('images')){
        $files=Input::file("images");
        foreach ($files as $key => $file) {
          $image = Image::make($file);
          $image->resize(500, 500);
          $extension = $file->getClientOriginalExtension();
          $checkImage=in_array($extension,$allowedImagefileExtension);
          $filename = time() . '-' .$file->getClientOriginalName();
          if($checkImage){
            $media = new \App\Media;
            $url = $destinationImages.'/'.$filename;
            $image->save($url);
            $media->name = $filename;
            $media->type = "image";
            $media->for = "project";
            $media->forId = $project->id;
            $media->status = "Active";
            $media->save();
            $color = "success";
          }
          else{
            $color = "danger";
            $message = "Only JPEG, JPG, PNG formats allowed for images!";
            return view("project.edit", compact('message', 'title', 'status', 'url', 'description', 'color'));
          }
        }
      }
      if($request->hasFile('videos')){
        $files=Input::file("videos");
        foreach ($files as $key => $file) {
          $extension = $file->getClientOriginalExtension();

resources/views/project/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
  <?php
  $project = \App\Project::find($id);
  ?>
        <div class="col-md-12">
          <div class="card bg-secondary shadow">
            @if(!empty($project->projectImage))
            <img class="card-img-top" src="{{asset('project/images/').'/'.$project->projectImage}}" height="500em" alt="Card image cap">
            @endif
            <?php
            $media = \App\Media::where('for', 'project')->where('forId', $project->id)->get();
            ?>
            <div class="card-body">
              @if(!$media->isEmpty())
              <div class="row text-center mt-4">
                @foreach($media as $value)
                @if($value->type == 'image')
                <div class="col-md-3">
                  <img class="img img-responsive col-md-12" src="{{asset('project/images/').'/'.$value->name}}">
                  <small class="col-md-12 text-center">{{$value->name}}</small>
                  <form action="{{ route('media.destroy', $value->id) }}" method="post" style="display:inline">
                    {{ method_field('DELETE') }}
                    {{ csrf_field() }}
                    <input hidden value="{{$project->id}}" name="forId">
                    <input hidden value="project" name="type">
                    <input type="submit" class="btn btn-danger btn-sm mt-2 mb-2" placeholder="Delete" value="Delete"/>
                  </form>
                </div>
                @elseif($value->type == 'video')
                <div class="col-md-3">
                  <video class="video col-md-12 mb-4" controls>
                    <source src="{{asset('project/videos/').'/'.$value->name}}">
                  </video>
                  <small class="col-md-12 text-center">{{$value->name}}</small>
                  <form action="{{ route('media.destroy', $value->id, $project->id, 'project') }}" method="post" style="display:inline">
                    <input hidden value="{{$project->id}}" name="forId">
                    <input hidden value="project" name="type">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                    <input type="submit" class="btn btn-danger btn-sm mt-2 mb-2" placeholder="Delete" value="Delete"/>
                  </form>
                </div>
                @endif
                @endforeach
              </div>
              @endif
              <form action="/projects/<?php echo $project->id ?>" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{ method_field('PUT')}}
                <input type="hidden" value="{{ $project->id}}" name="id">
                <div>
                  <div class="row">
                      <div class="col-lg-12">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Title</label>
                        <input type="text" required id="input-postal-code" name="name" class="form-control form-control-alternative" placeholder="Title"  value="{{ $project->title}}" >
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Project Owner</label>
                        <input type="text" required id="input-postal-code" name="projectOwner" class="form-control form-control-alternative" placeholder="Project Owner"  value="{{ $project->projectOwner}}" >
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Collaboration Date</label>
                        <div class="input-group input-group-alternative">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="ni ni-calendar-grid-58"></i></span>
                            </div>
                            <input value="{{$project->collaborationDate}}" class="form-control datepicker" name="collabrationDate" placeholder="Select date" type="text">
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                          <div class="form-group">
                        <label class="form-control-label" for="input-country">Link</label>
                        <input type="url" required id="input-postal-code" name="link" class="form-control form-control-alternative" placeholder="Link"  value="{{ $project->URL}}" >
                      </div>
                    </div>
                         <div class="col-lg-6">
                           <div class="form-group">
                             <label class="form-control-label" for="input-country">Status</label>
                             <select required name="status" class="form-control form-control-alternative">
                               @if($project->status=='Active')
                               <option value="Active" selected>Active</option>
                               <option value="Deactive">Deactive</option>
                               @elseif($project->status=='Deactive')
                               <option value="Active">Active</option>
                               <option value="Deactive" selected>Deactive</option>
                               @endif
                             </select>
                           </div>
                         </div>
                         <div class="col-lg-6">
                            <div class="form-group">
                              <label class="form-control-label" for="input-email">Primary Image <small>(Only PNG, JPG, JPEG formats allowed)</small></label>
                              <label class="btn btn-success" for="image"><i class="fas fa-upload"></i> Upload Image</label><small id="imageLabel"></small>
                              <input type="file" id="image" style="position:absolute; opacity:0; z-index:-1" name="image" class="form-control form-control-alternative" accept=".jpg,.jpeg,.png">
                             </div>
                         </div>
                         <div class="col-lg-6">
                           <div class="form-group">
                             <label class="form-control-label" for="input-email">Images <small>(Only PNG, JPG, JPEG formats allowed)</small></label><br>
                             <label class="btn btn-success" for="images"><i class="fas fa-upload"></i> Upload Images</label><small id="imagesLabel"></small>
                             <input type="file" id="images" style="position:absolute; opacity:0; z-index:-1" name="images[]" class="form-control form-control-alternative" accept=".jpg,.jpeg,.png" multiple>
                             </div>
                         </div>
                         <div class="col-lg-6">
                           <div class="form-group">
                             <label class="form-control-label" for="input-email">Videos <small>(Only FLV, MP4, M4P, MPEG, MOV formats allowed)</small></label>
                             <label class="btn btn-success" for="videos"><i class="fas fa-upload"></i> Upload Videos</label><small id="videosLabel"></small>
                             <input type="file" id="videos" style="position:absolute; opacity:0; z-index:-1" name="videos[]" class="form-control form-control-alternative" accept=".mp4,.m4p,.mpeg,.webm,.mov,.mpg,.flv" multiple>
                             </div>
                         </div>
                         <div class="col-md-12">
                           <div class="form-group">
                             <?php
                             $descriptionUrl = "/project/"."/".$project->description;
                             $description = Storage::get($descriptionUrl);
                             ?>

                             <label class="form-control-label" for="input-username">Project Description</label>
                             <textarea class="form-control" rows="5" name="editor1" value="{{$project->description}}" required>{!!html_entity_decode($description)!!}</textarea>
                           </div>
                         </div>
                         <?php
                         $CommentUrl = "/project-comments/"."/".$project->projectOwnerComment;
                         $comment = Storage::get($CommentUrl);
                         ?>
                         <div class="col-md-12">
                           <div class="form-group">
                             <label class="form-control-label" for="input-username">Project Owner Comments</label>
                             <textarea class="form-control" rows="5" name="comments"  value="{{ $project->projectOwnerComment }}" required>{!!html_entity_decode($comment)!!}</textarea>
                           </div>
                         </div>
                    </div>
                </div>
                <!-- Save Button -->
                <div class="row">
                  <div class="col-md-12 text-right">
                    <input class="btn btn-default" type="submit" value="Update"></input>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'danger'
@endsection
@endif

resources/views/project/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
        <div class="col">
          <div class="card shadow">
            <div class="card-header border-0">

              <h3 class="mb-0">Project
                <div style="display: inline; float: right" >
                  <a type="link" class="btn btn-sm btn-primary pull-right" href="{{URL::asset('projects/create')}}">Add Project</a>
                </div>
              </h3>

            </div>
            <?php
            $projects = \App\Project::all()->sortByDesc("id");
            ?>
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Status</th>
                    <th scope="col">Control Section</th>
                  </tr>
                </thead>
                <tbody>



                  @foreach($projects as $info)
                  <tr>
                    <td>{{$info->id}}</td>
                    <th scope="row">
                      <div class="media align-items-center">
                        <a href="#" class="avatar rounded-circle mr-3">
                          <img src="{{asset('project/images/').'/'.$info->projectImage}}" alt="Project Image" />
                        </a>
                        <div class="media-body">
                          <span class="mb-0 text-sm">{{$info->title}}</span>
                        </div>
                      </div>
                    </th>
                    <td>
                      <span class="badge badge-dot mr-4">
                        @if($info->status == 'Deactive')
                        <i class="bg-warning"></i> Deactive
                        @elseif($info->status == 'Active')
                        <i class="bg-success"></i> Active
                        @endif
                      </span>
                    </td>
                    <td>
                        <a type="link" class="btn btn-success btn-sm" href="/projects/<?php echo $info->id; ?>">View</a>
                        <a type="link" class="btn btn-default btn-sm" href="/projects/<?php echo $info->id;?>/edit">Edit</a>
                        <form action="{{ route('projects.destroy', $info->id) }}" method="post" style="display:inline">
                                  {{ method_field('DELETE') }}
                                  {{ csrf_field() }}
                          <input type="submit" class="btn btn-danger btn-sm" placeholder="Delete" value="Delete"/>
                        </form>
                    </td>
                  </tr>


                  @endforeach

                </tbody>
              </table>
            </div>

          </div>
        </div>
      </div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'<?php echo $color; ?>'
@endsection
@endif

resources/views/project/show.blade.php
@extends('layouts.app')
@section('content')
<div class="card" class="col-md-12">
  <?php
  $project = \App\Project::find($id);
  ?>
  <img class="card-img-top" src="{{asset('project/images/').'/'.$project->projectImage}}" height="500em" alt="Card image cap">
  <div class="card-body">
    <h2 class="card-title">{{$project->title}} <small>({{$project->status}})</small></h2>
    <p><a href="{{$project->URL}}" target="_new">Visit</a></p>

    <div class="row">
      <div class="col-md-6">
        <p class="card-text"><b>Uploaded By:</b></p>
        <p class="card-text"><b>Project Owner</b></p>
        <p class="card-text"><b>Collaboration Date:</b></p>
        <p class="card-text"><b>Owner Comments:</b></p>

      </div>
      <div class="col-md-6">
        <?php $uploader = \App\User::find($project->uploaderID); ?>
        <p class="card-text">{{$uploader->name}}</p>
        <p class="card-text">{{$project->projectOwner}}</p>
        <p class="card-text">{{$project->collaborationDate}}</p>
      </div>
      <div class="col-md-12">
        <?php
        $commentUrl = "/project-comments/"."/".$project->projectOwnerComment;
        $comment = Storage::get($commentUrl);
        ?>
        {!!html_entity_decode($comment)!!}
      </div>

      <div class="col-md-12">
        <p class="card-text"><b>Description:</b></p>
        <?php
        $descriptionUrl = "/project/"."/".$project->description;
        $description = Storage::get($descriptionUrl);
        ?>
        {!!html_entity_decode($description)!!}
      </div>
    </div>
  </div>
</div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'danger'
@endsection
@endif