routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/applicationForm/{id}', 'ApplicantController@apply');
Route::get('/viewJob/{id}', 'CareerController@viewJob');
Route::get('/viewAllJobs', function () {
    return view('viewAllJobs');
});
Route::get('/', function () {
  $message = "Welcome to OnSets!";
    return view('welcome', compact('message'));
});
Route::resource('/queries', 'QueryController');
Route::resource('/subcribeEmails', 'SubscribeController');
Route::get('/differnt/{status}', 'QueryController@DifferentQuery');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/ourinfo', 'HomeController@ourinfo');
Route::get('/viewAllStories', 'HomeController@viewAllStories');
Route::post('/ourinfoAdd', 'HomeController@ourinfoAdd');
Route::post('/ourinfoUpdate/{id}', 'HomeController@ourinfoUpdate');
Route::get('/viewApplicants/{id}', 'ApplicantController@viewApplicants');
Route::resource('/addresses', 'AddressController');
Route::resource('/products', 'ProductController');
Route::resource('/projects', 'ProjectController');
Route::resource('/careers', 'CareerController');
Route::resource('/stories', 'StoryController');
Route::resource('/roles', 'RoleController');
Route::resource('/applicants', 'ApplicantController');
Route::resource('/users', 'userController');
Route::resource('/contacts', 'ContactController');


Route::post('/usersContact', 'userController@infoAddContact');
Route::post('/usersAddress', 'userController@infoAddAddress');
Route::post('/usersContactD/{id}/{contact}', 'userController@infoDeleteContact');
Route::post('/usersAddressD/{id}/{address}', 'userController@infoDeleteAddress');
Route::get('/userContact/{id}', 'userController@AddContactView');
Route::get('/userAddress/{id}', 'userController@AddAddressView');
Route::get('/ContactEdit/{id}/{contact}', 'userController@EditContactView');
Route::get('/AddressEdit/{id}/{address}', 'userController@EditAddressView');
Route::post('/UpdateContact/{id}', 'userController@UpdateContact');
Route::post('/updateAddress/{id}', 'userController@updateAddress');


Route::resource('/media', 'MediaController');
Route::resource('/sliders', 'SliderController');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //

    protected $table = 'products';
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Product;
use App\Http\Controllers\Controller;
use Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Redirect;
use File;
use Intervention\Image\ImageManager;
use Intervention\Image\ImageManagerStatic as Image;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct()
     {
         $this->middleware('auth');
     }

    public function index()
    {
        return view('product.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $product = new Product;
      $title = $request->get('title');
      $url = $request->get('url');
      $status = $request->get('status');
      $description = $request->get('editor1');
      $product->productName = $title;
      $product->productURL = $url;
      $product->uploaderID = Auth::id();
      $product->status = $status;

      $destinationImages='product/images';
      $allowedImagefileExtension=['jpg','png','jpeg'];
      $destinationVideo='product/videos';
      $allowedVideofileExtension=['mp4','flv','m4p','mpg','mpeg','webm','mov'];
      $productDescriptionFile = time();
      $productDescriptionUrl = "/product/".$productDescriptionFile.".txt";
      Storage::put($productDescriptionUrl, $description);
      $product->description = $productDescriptionFile.".txt";

      if($request->hasFile('image')){
        $file=Input::file("image");
        $extension = $file->getClientOriginalExtension();
        $checkImage=in_array($extension,$allowedImagefileExtension);
        $checkVideo=in_array($extension,$allowedVideofileExtension);
        $filename = time() . '-' .$file->getClientOriginalName();
        if($checkImage){
          $image = Image::make($file);
          //$image->resize(500, 500);
          $url = $destinationImages.'/'.$filename;

          if (!file_exists($destinationImages)) {
            mkdir($destinationImages, 666, true);
          }

          $image->save($url);
          $product->productImage = $filename;
        }
        elseif($checkVideo){
          $file->move($destinationVideo,$filename);
          $product->productVideo = $filename;
        }
        else{
          $message = "Only JPEG, JPG, PNG formats allowed for images!";
          $color = "danger";
          return view("product.create", compact('message', 'title', 'status', 'url', 'description', 'color'));
        }
        $product->save();
        $color = "success";
      }

      if($request->hasFile('images')){
        $files=Input::file("images");
        foreach ($files as $key => $file) {
          $extension = $file->getClientOriginalExtension();
          $checkImage=in_array($extension,$allowedImagefileExtension);
          $filename = time() . '-' .$file->getClientOriginalName();
          if($checkImage){
            $image = Image::make($file);
            $image->resize(500, 500);
            $media = new \App\Media;
            $url = $destinationImages.'/'.$filename;

            if (!file_exists($destinationImages)) {
              mkdir($destinationImages, 666, true);
            }
            

            $image->save($url);
            $media->name = $filename;
            $media->type = "image";
            $media->for = "product";
            $media->forId = $product->id;
            $media->status = "Active";
            $media->save();
          }
          else{
            $message = "Only JPEG, JPG, PNG formats allowed for images!";
            $color = "danger";
            return view("product.create", compact('message', 'title', 'status', 'url', 'description', 'color'));
          }
        }
      }
      if($request->hasFile('videos')){
        $files=Input::file("videos");
        foreach ($files as $key => $file) {
          $extension = $file->getClientOriginalExtension();
          $checkVideo=in_array($extension,$allowedVideofileExtension);
          $filename = time() . '-' .$file->getClientOriginalName();
          if($checkVideo){
            $media = new \App\Media;
            $file->move($destinationVideo,$filename);
            $media->name = $filename;
            $media->type = "video";
            $media->for = "product";
            $media->forId = $product->id;
            $media->status = "Active";
            $media->save();
          }
          else{
            $message = "Only MP4, M4P, MOV, WEBM, MPEG, FLV formats allowed for videos!";
            $color = "danger";
            return view("product.create", compact('message', 'title', 'status', 'url', 'description', 'color'));
          }
        }
      }
      $message = "Product Saved";
      return view('product.index', compact('message', 'color'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $product = \App\Product::find($id);
      return view('product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('product.edit', compact('id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $product = Product::find($id);
      $title = $request->get('title');
      $url = $request->get('url');
      $status = $request->get('status');
      $description = $request->get('editor1');
      $product->productName = $title;
      $product->productURL = $url;
      $product->uploaderID = Auth::id();
      $product->status = $status;
      $destinationImages='product/images';
      $allowedImagefileExtension=['jpg','png','jpeg'];
      $destinationVideo='product/videos';
      $allowedVideofileExtension=['mp4','flv','m4p','mpg','mpeg','webm','mov'];
      $productDescriptionUrl = "/product/".$product->description;
      Storage::put($productDescriptionUrl, $description);
      $product->save();
      $color = "success";
      if($request->hasFile('image')){
        $file=Input::file("image");
        $extension = $file->getClientOriginalExtension();
        $checkImage=in_array($extension,$allowedImagefileExtension);
        $checkVideo=in_array($extension,$allowedVideofileExtension);
        $filename = time() . '-' .$file->getClientOriginalName();
        if($checkImage){
          if(!empty($product->productImage)){
            $path = 'product/images/'.$product->productImage;
            File::delete($path);
            $product->productImage = null;
          }
          elseif(!empty($product->productVideo)){
            $path = 'product/videos/'.$product->productVideo;
            File::delete($path);
            $product->productVideo = null;
          }
          $image = Image::make($file);
          //$image->resize(500, 500);
          $url = $destinationImages.'/'.$filename;
          $image->save($url);
          $product->productImage = $filename;
        }
        elseif($checkVideo){
          if(!empty($product->productImage)){
            $path = 'product/images/'.$product->productImage;
            File::delete($path);
            $product->productImage = null;
          }
          elseif(!empty($product->productVideo)){
            $path = 'product/videos/'.$product->productVideo;
            $product->productVideo = null;
            File::delete($path);
          }
          $file->move($destinationVideo,$filename);
          $product->productVideo = $filename;
        }
        else{
          $message = "Only JPEG, JPG, PNG formats allowed for images!";
          $color = "danger";
          return view("product.create", compact('message', 'title', 'status', 'url', 'description', 'color'));
        }
        $product->save();
        $color = "success";
      }
      if($request->hasFile('images')){
        $files=Input::file("images");
        foreach ($files as $key => $file) {
          $extension = $file->getClientOriginalExtension();
          $checkImage=in_array($extension,$allowedImagefileExtension);
          $filename = time() . '-' .$file->getClientOriginalName();
          if($checkImage){
            $image = Image::make($file);
            $image->resize(500, 500);
            $media = new \App\Media;
            $url = $destinationImages.'/'.$filename;
            $image->save($url);
            $media->name = $filename;
            $media->type = "image";
            $media->for = "product";
            $media->forId = $product->id;
            $media->status = "Active";
            $media->save();
            $color = "success";
          }
          else{
            $color = "danger";
            $message = "Only JPEG, JPG, PNG formats allowed for images!";
            return view("product.edit", compact('message', 'title', 'status', 'url', 'description', 'color'));
          }
        }
      }
      if($request->hasFile('videos')){
        $files=Input::file("videos");
        foreach ($files as $key => $file) {
          $extension = $file->getClientOriginalExtension();
          $checkVideo=in_array($extension,$allowedVideofileExtension);
          $filename = time() . '-' .$file->getClientOriginalName();
          if($checkVideo){
            $media = new \App\Media;

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
        <div class="col-md-12">
          <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">Product</h3>
                </div>
              </div>
            </div>
            <div class="card-body">
              <form action="/products" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div>
                  <div class="row">
                      <div class="col-lg-12">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Title</label>
                        <input required type="text" id="input-postal-code" name="title" class="form-control form-control-alternative" placeholder="Title">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Link</label>
                        <input required name="url" type="url" id="input-postal-code" class="form-control form-control-alternative" placeholder="Link">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Status</label>
                        <select required name="status" class="form-control form-control-alternative">
                          <option value="Active">Active</option>
                          <option value="Deactive">Deactive</option>
                        </select>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group">
                        <label class="form-control-label" for="input-username">Description</label>
                        <textarea name="editor1" class="form-control" required placeholder="Description" rows="5"></textarea>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Primary Image <small>(Only PNG, JPG, JPEG formats allowed)</small></label>
                        <label class="btn btn-success" for="image"><i class="fas fa-upload"></i> Upload Image</label><small id="imageLabel"></small>
                        <input id="image" style="position:absolute; opacity:0; z-index:-1" type="file" name="image" required class="form-control form-control-alternative" accept=".jpg,.jpeg,.png">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Images <small>(Only PNG, JPG, JPEG formats allowed)</small></label><br>
                        <label class="btn btn-success" for="images"><i class="fas fa-upload"></i> Upload Images</label><small id="imagesLabel"></small>
                        <input type="file" id="images" style="position:absolute; opacity:0; z-index:-1" name="images[]" class="form-control form-control-alternative" accept=".jpg,.jpeg,.png" multiple>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Videos <small>(Only FLV, MP4, M4P, MPEG, MOV formats allowed)</small></label>
                        <label class="btn btn-success" for="videos"><i class="fas fa-upload"></i> Upload Videos</label><small id="videosLabel"></small>
                        <input type="file" id="videos" style="position:absolute; opacity:0; z-index:-1" name="videos[]" class="form-control form-control-alternative" accept=".mp4,.m4p,.mpeg,.webm,.mov,.mpg,.flv" multiple>
                      </div>
                    </div>
                    <div class="col-md-12 text-right">
                      <input class="btn btn-default" type="submit" value="Save"></input>
                    </div>
                  </div>
                </div>
                <!-- Save Button -->
              </form>
            </div>
          </div>
        </div>
      </div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'danger'
@endsection
@endif

resources/views/product/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
        <div class="col-md-12">
          <div class="card bg-secondary shadow">
            <?php
            $product = \App\Product::find($id);
            ?>
            <img class="card-img-top" src="{{asset('product/images/').'/'.$product->productImage}}" height="500em" alt="Card image cap">
            <?php
            $media = \App\Media::where('for', 'product')->where('forId', $product->id)->get();
            ?>
            @if(!$media->isEmpty())
            <div class="row text-center mt-4">
              @foreach($media as $value)
              @if($value->type == 'image')
              <div class="col-md-3">
                <img class="img img-responsive col-md-12" src="{{asset('product/images/').'/'.$value->name}}">
                <small class="col-md-12 text-center">{{$value->name}}</small>
                <form action="{{ route('media.destroy', $value->id) }}" method="post" style="display:inline">
                          {{ method_field('DELETE') }}
                          {{ csrf_field() }}
                          <input hidden value="{{$product->id}}" name="forId">
                          <input hidden value="product" name="type">
                  <input type="submit" class="btn btn-danger btn-sm mt-2 mb-2" placeholder="Delete" value="Delete"/>
                </form>
              </div>
              @elseif($value->type == 'video')
              <div class="col-md-3">
                <video class="video col-md-12 mb-4" controls>
                  <source src="{{asset('product/videos/').'/'.$value->name}}">
                </video>
                <small class="col-md-12 text-center">{{$value->name}}</small>
                <form action="{{ route('media.destroy', $value->id, $product->id, 'product') }}" method="post" style="display:inline">
                  <input hidden value="{{$product->id}}" name="forId">
                  <input hidden value="product" name="type">
                          {{ method_field('DELETE') }}
                          {{ csrf_field() }}
                  <input type="submit" class="btn btn-danger btn-sm mt-2 mb-2" placeholder="Delete" value="Delete"/>
                </form>
              </div>
              @endif
              @endforeach
            </div>
            @endif
            <div class="card-body">
              <form action="/products/<?php echo $product->id;?>" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{method_field('PUT')}}
                <div>
                  <div class="row">
                      <div class="col-lg-12">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Title</label>
                        <input required type="text" id="input-postal-code" name="title" value="{{$product->productName}}" class="form-control form-control-alternative" placeholder="Title">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Link</label>
                        <input value="{{$product->productURL}}" required name="url" type="text" id="input-postal-code" class="form-control form-control-alternative" placeholder="Link">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Status</label>
                        <select required name="status" class="form-control form-control-alternative">
                          @if($product->status=='Active')
                          <option value="Active" selected>Active</option>
                          <option value="Deactive">Deactive</option>
                          @elseif($product->status=='Deactive')
                          <option value="Active">Active</option>
                          <option value="Deactive" selected>Deactive</option>
                          @endif
                        </select>
                      </div>
                    </div>
                    <div class="col-md-12">
                      <div class="form-group">
                        <label class="form-control-label" for="input-username">Description</label>
                        <?php
                        $descriptionUrl = "/product/"."/".$product->description;
                        $description = Storage::get($descriptionUrl);
                        ?>
                        <textarea class="form-control" rows="5" name="editor1" value="{{$product->description}}" required placeholder="Description">{!!html_entity_decode($description)!!}</textarea>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Primary Image <small>(Only PNG, JPG, JPEG formats allowed)</small></label>
                        <label class="btn btn-success" for="image"><i class="fas fa-upload"></i> Upload Image</label><small id="imageLabel"></small>
                        <input type="file" id="image" style="position:absolute; opacity:0; z-index:-1" name="image" class="form-control form-control-alternative" accept=".jpg,.jpeg,.png">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Images <small>(Only PNG, JPG, JPEG formats allowed)</small></label><br>
                        <label class="btn btn-success" for="images"><i class="fas fa-upload"></i> Upload Images</label><small id="imagesLabel"></small>
                        <input type="file" id="images" style="position:absolute; opacity:0; z-index:-1" name="images[]" class="form-control form-control-alternative" accept=".jpg,.jpeg,.png" multiple>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Videos <small>(Only FLV, MP4, M4P, MPEG, MOV formats allowed)</small></label>
                        <label class="btn btn-success" for="videos"><i class="fas fa-upload"></i> Upload Videos</label><small id="videosLabel"></small>
                        <input type="file" id="videos" style="position:absolute; opacity:0; z-index:-1" name="videos[]" class="form-control form-control-alternative" accept=".mp4,.m4p,.mpeg,.webm,.mov,.mpg,.flv" multiple>
                      </div>
                    </div>
                    <div class="col-md-12 text-right">
                      <input class="btn btn-default" type="submit" value="Update"></input>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'danger'
@endsection
@endif

resources/views/product/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
        <div class="col">
          <div class="card shadow">
            <div class="card-header border-0">
              <h3 class="mb-0">Product
                <div style="display: inline; float: right" >
                  <a type="link" class="btn btn-sm btn-primary pull-right" href="{{URL::asset('products/create')}}">Add Product</a>
                </div>
              </h3>
            </div>
            <?php
            $products = \App\Product::all()->sortByDesc("id");
            ?>
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Status</th>
                    <th scope="col">Control Section</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($products as $info)
                  <tr>
                    <td>{{$info->id}}</td>
                    <th scope="row">
                      <div class="media align-items-center">
                        <a href="#" class="avatar rounded-circle mr-3">
                          <img src="{{asset('product/images/').'/'.$info->productImage}}" alt="Product Image" />
                        </a>
                        <div class="media-body">
                          <span class="mb-0 text-sm">{{$info->productName}}</span>
                        </div>
                      </div>
                    </th>
                    <td>
                      <span class="badge badge-dot mr-4">
                        @if($info->status == 'Deactive')
                        <i class="bg-warning"></i> Deactive
                        @elseif($info->status == 'Active')
                        <i class="bg-success"></i> Active
                        @endif
                      </span>
                    </td>
                    <td>
                        <a type="link" class="btn btn-success btn-sm" href="/products/<?php echo $info->id; ?>">View</a>
                        <a type="link" class="btn btn-default btn-sm" href="/products/<?php echo $info->id;?>/edit">Edit</a>
                        <form action="{{ route('products.destroy', $info->id) }}" method="post" style="display:inline">
                                  {{ method_field('DELETE') }}
                                  {{ csrf_field() }}
                          <input type="submit" class="btn btn-danger btn-sm" placeholder="Delete" value="Delete"/>
                        </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>

          </div>
        </div>
      </div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
@if(!empty($color))
'<?php echo $color; ?>'
@endif
@endsection
@endif

resources/views/product/show.blade.php
@extends('layouts.app')

@section('content')
<div class="card" class="col-md-12">
  <img class="card-img-top" src="{{asset('product/images/').'/'.$product->productImage}}" height="500em" alt="Card image cap">
  <div class="card-body">
    <h2 class="card-title">{{$product->productName}} <small>({{$product->status}})</small>
      <?php
      $uploader = \App\User::find($product->uploaderID);
      ?>
      <div style="display:inline; float: right">
      <small><b>Uploaded By:</b> {{$uploader->name}}</small></div>
    </h2>
    <p><a href="{{$product->productURL}}" target="_new">View {{$product->productName}}</a></p>
    <p class="card-text" id="desc">
    <?php
    $descriptionUrl = "/product/"."/".$product->description;
    $description = Storage::get($descriptionUrl);
    ?>
    {!!html_entity_decode($description)!!}
    </p>
  </div>
</div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'danger'
@endsection
@endif