routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/applicationForm/{id}', 'ApplicantController@apply');
Route::get('/viewJob/{id}', 'CareerController@viewJob');
Route::get('/viewAllJobs', function () {
    return view('viewAllJobs');
});
Route::get('/', function () {
  $message = "Welcome to OnSets!";
    return view('welcome', compact('message'));
});
Route::resource('/queries', 'QueryController');
Route::resource('/subcribeEmails', 'SubscribeController');
Route::get('/differnt/{status}', 'QueryController@DifferentQuery');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/ourinfo', 'HomeController@ourinfo');
Route::get('/viewAllStories', 'HomeController@viewAllStories');
Route::post('/ourinfoAdd', 'HomeController@ourinfoAdd');
Route::post('/ourinfoUpdate/{id}', 'HomeController@ourinfoUpdate');
Route::get('/viewApplicants/{id}', 'ApplicantController@viewApplicants');
Route::resource('/addresses', 'AddressController');
Route::resource('/products', 'ProductController');
Route::resource('/projects', 'ProjectController');
Route::resource('/careers', 'CareerController');
Route::resource('/stories', 'StoryController');
Route::resource('/roles', 'RoleController');
Route::resource('/applicants', 'ApplicantController');
Route::resource('/users', 'userController');
Route::resource('/contacts', 'ContactController');


Route::post('/usersContact', 'userController@infoAddContact');
Route::post('/usersAddress', 'userController@infoAddAddress');
Route::post('/usersContactD/{id}/{contact}', 'userController@infoDeleteContact');
Route::post('/usersAddressD/{id}/{address}', 'userController@infoDeleteAddress');
Route::get('/userContact/{id}', 'userController@AddContactView');
Route::get('/userAddress/{id}', 'userController@AddAddressView');
Route::get('/ContactEdit/{id}/{contact}', 'userController@EditContactView');
Route::get('/AddressEdit/{id}/{address}', 'userController@EditAddressView');
Route::post('/UpdateContact/{id}', 'userController@UpdateContact');
Route::post('/updateAddress/{id}', 'userController@updateAddress');


Route::resource('/media', 'MediaController');
Route::resource('/sliders', 'SliderController');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    //
}

app/Http/Controllers/SliderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Redirect;
use File;
use Intervention\Image\ImageManagerStatic as Image;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct()
     {
         $this->middleware('auth');
     }

    public function index()
    {
        return view('slider.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('slider.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $slider = new \App\Slider;
      $content = $request->get('content');
      $sliderContentFile = time();
      $sliderContentUrl = "/slider/".$sliderContentFile.".txt";
      Storage::put($sliderContentUrl, $content);
      $slider->content = $sliderContentFile.".txt";
      $slider->status = $request->get('status');

      $destinationImages='slider/images';
      $allowedImagefileExtension=['jpg','png','jpeg'];
      $destinationVideo='slider/videos';
      $allowedVideofileExtension=['mp4','flv','m4p','mpg','mpeg','webm','mov'];
      $slider->uploaderID = Auth::id();
      $slider->save();
      if($request->hasFile('file')){
        $file=Input::file("file");
        $extension = $file->getClientOriginalExtension();
        $checkImage=in_array($extension,$allowedImagefileExtension);
        $checkVideo=in_array($extension,$allowedVideofileExtension);
        $filename = time() . '-' .$file->getClientOriginalName();
        if($checkImage){
          $image = Image::make($file);
          $image->resize(500, 500);
          $media = new \App\Media;
          $url = $destinationImages.'/'.$filename;
          if (!file_exists($destinationImages)) {
            mkdir($destinationImages, 666, true);
          }
          $image->save($url);
          $media->name = $filename;
          $media->type = "image";
          $media->for = "slider";
          $media->forId = $slider->id;
          $media->status = "Active";
          $media->save();
        }
        elseif($checkVideo){
          $media = new \App\Media;
          $file->move($destinationVideo,$filename);
          $media->name = $filename;
          $media->type = "video";
          $media->for = "slider";
          $media->forId = $slider->id;
          $media->status = "Active";
          $media->save();
        }
        else{
          $message = "Only JPEG, JPG, PNG formats allowed for images!";
          $color = "danger";
          return view("slider.create", compact('message', 'title', 'status', 'url', 'description', 'color'));
        }
      }
      $color = "success";
      $message = "Slider Saved!";
      return view('slider.index', compact('color', 'message'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('slider.show', compact('id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      return view('slider.edit', compact('id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $slider = \App\Slider::find($id);
      $content = $request->get('content');
      $sliderContentFile = $slider->content;
      $sliderContentUrl = "/slider/".$sliderContentFile;
      Storage::put($sliderContentUrl, $content);
      $slider->status = $request->get('status');
      $slider->uploaderID = Auth::id();
      $slider->save();

      $destinationImages='slider/images';
      $allowedImagefileExtension=['jpg','png','jpeg'];
      $destinationVideo='slider/videos';
      $allowedVideofileExtension=['mp4','flv','m4p','mpg','mpeg','webm','mov'];

      if($request->hasFile('file')){
        $file=Input::file("file");
        $extension = $file->getClientOriginalExtension();
        $checkImage=in_array($extension,$allowedImagefileExtension);
        $checkVideo=in_array($extension,$allowedVideofileExtension);
        $filename = time() . '-' .$file->getClientOriginalName();
        if($checkImage){
          $media = \App\Media::where('for', 'slider')->where('forId', $slider->id)->first();
          if(!empty($media)){
            $path = 'slider/images/'.$media->name;
            File::delete($path);
            $media->delete();
          }
          $image = Image::make($file);
          $image->resize(500, 500);
          $media = new \App\Media;
          $url = $destinationImages.'/'.$filename;
          if (!file_exists($destinationImages)) {
            mkdir($destinationImages, 666, true);
          }
          $image->save($url);
          $media->name = $filename;
          $media->type = "image";
          $media->for = "slider";
          $media->forId = $slider->id;
          $media->status = "Active";
          $media->save();
        }
        elseif($checkVideo){
          $media = \App\Media::where('for', 'slider')->where('forId', $slider->id)->first();
          $path = 'slider/video/'.$media->name;
          File::delete($path);
          $media->delete();
          $media = new \App\Media;
          $file->move($destinationVideo,$filename);
          $media->name = $filename;
          $media->type = "video";
          $media->for = "slider";
          $media->forId = $slider->id;
          $media->status = "Active";
          $media->save();
        }
        else{
          $message = "Only JPEG, JPG, PNG formats allowed for images!";
          $color = "danger";
          return view("slider.create", compact('message', 'title', 'status', 'url', 'description', 'color'));
        }
      }
      $slider->save();
      $color = "success";
      $message = "Slider Updated";
      return view('slider.index', compact('color', 'message'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function destroy($id)
    {
      $slider = \App\Slider::find($id);

      $contentFile=$slider->content;
      Storage::delete('slider/'.$contentFile);

      $media = \App\Media::where('for', 'slider')->where('forId', $id)->get();
      foreach ($media as $key => $value) {
        if($value->type == 'image'){
          $path = 'slider/images/'.$value->name;
          File::delete($path);
        }
        elseif($value->type == 'video'){
          $path = 'slider/videos/'.$value->name;
          File::delete($path);
        }
        $value->delete();
      }

      if($slider->delete()){
        $message = "Slider Delete";
        $color='success';
        return view('slider.index' , compact('message','color'));
      }
      else{
        $message = "Slider not Delete";
        $color='danger';
        return view('slider.index' , compact('message','color'));
      }

    }
}

resources/views/slider/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
        <div class="col-md-12">
          <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">Slider</h3>
                </div>
              </div>
            </div>
            <div class="card-body">
              <form action="/sliders" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Primary Image <small>(Only PNG, JPG, JPEG formats allowed)</small></label>
                        <label class="btn btn-success" for="image"><i class="fas fa-upload"></i> Upload Image</label><small id="imageLabel"></small>
                        <input type="file" id="image" style="position:absolute; opacity:0; z-index:-1" name="file" class="form-control form-control-alternative" accept=".jpg,.jpeg,.png, .flv, .mp4, .mov, .wemb, .mpeg">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Status</label>
                        <select required name="status" class="form-control form-control-alternative">
                          <option value="Active">Active</option>
                          <option value="Deactive">Deactive</option>
                        </select>
                      </div>
                    </div>
                       <div class="col-md-12">
                           <div class="form-group">
                             <label class="form-control-label" for="input-username">Content</label>
                             <textarea class="form-control" rows="5" name="content" placeholder="Content"></textarea>
                           </div>
                         </div>
                    </div>
                </div>
                <!-- Save Button -->
                <div class="row">
                  <div class="col-12 text-right">
                    <input class="btn btn-default" type="submit" value="Save"></input>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'danger'
@endsection
@endif

resources/views/slider/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
  <?php $slider = \App\Slider::find($id); ?>
        <div class="col-md-12">
          <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">Slider</h3>
                </div>
              </div>
            </div>
            <div class="card-body">
              <?php
              $media = \App\Media::where('for', 'slider')->where('forId', $slider->id)->get();
              ?>
              @if(!$media->isEmpty())
              <div class="row text-center mt-4">
                @foreach($media as $value)
                @if($value->type == 'image')
                <div class="col-md-3">
                  <img class="img img-responsive col-md-12" src="{{asset('slider/images/').'/'.$value->name}}">
                  <small class="col-md-12 text-center">{{$value->name}}</small>
                  <form action="{{ route('media.destroy', $value->id) }}" method="post" style="display:inline">
                    {{ method_field('DELETE') }}
                    {{ csrf_field() }}
                    <input hidden value="{{$slider->id}}" name="forId">
                    <input hidden value="slider" name="type">
                    <input type="submit" class="btn btn-danger btn-sm mt-2 mb-2" placeholder="Delete" value="Delete"/>
                  </form>
                </div>
                @elseif($value->type == 'video')
                <div class="col-md-3">
                  <video class="video col-md-12 mb-4" controls>
                    <source src="{{asset('slider/videos/').'/'.$value->name}}">
                  </video>
                  <small class="col-md-12 text-center">{{$value->name}}</small>
                  <form action="{{ route('media.destroy', $value->id, $slider->id, 'project') }}" method="post" style="display:inline">
                    <input hidden value="{{$slider->id}}" name="forId">
                    <input hidden value="slider" name="type">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                    <input type="submit" class="btn btn-danger btn-sm mt-2 mb-2" placeholder="Delete" value="Delete"/>
                  </form>
                </div>
                @endif
                @endforeach
              </div>
              @endif
              <form action="/sliders/<?php echo $slider->id ?>" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{method_field('PUT')}}
                <div>
                  <div class="row">
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Primary Image <small>(Only PNG, JPG, JPEG formats allowed)</small></label>
                        <label class="btn btn-success" for="image"><i class="fas fa-upload"></i> Upload Image</label><small id="imageLabel"></small>
                        <input type="file" id="image" style="position:absolute; opacity:0; z-index:-1" name="file" class="form-control form-control-alternative" accept=".jpg,.jpeg,.png, .flv, .mp4, .mov, .wemb, .mpeg">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Status</label>
                        <select required name="status" class="form-control form-control-alternative">
                          @if($slider->status=='Active')
                          <option value="Active" selected>Active</option>
                          <option value="Deactive">Deactive</option>
                          @elseif($slider->status=='Deactive')
                          <option value="Active">Active</option>
                          <option value="Deactive" selected>Deactive</option>
                          @endif
                        </select>
                      </div>
                    </div>
                      <div class="col-md-12">
                         <div class="form-group">
                           <?php
                           $contentUrl = "/slider/"."/".$slider->content;
                           $content = Storage::get($contentUrl);
                           ?>
                           <label class="form-control-label" for="input-username">Content</label>
                           <textarea class="form-control" rows="5" name="content" placeholder="Content">{!!html_entity_decode($content)!!}</textarea>
                         </div>
                       </div>
                    </div>
                </div>
                <!-- Save Button -->
                <div class="row">
                  <div class="col-12 text-right">
                    <input class="btn btn-default" type="submit" value="Save"></input>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'danger'
@endsection
@endif

resources/views/slider/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
        <div class="col">
          <div class="card shadow">
            <div class="card-header border-0">

              <h3 class="mb-0">Sliders
                <div style="display: inline; float: right" >
                  <a type="link" class="btn btn-sm btn-primary pull-right" href="{{URL::asset('sliders/create')}}">Add Slider</a>
                </div>
              </h3>
            </div>
            <?php
            $sliders = \App\Slider::all();
            ?>
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Status</th>
                    <th scope="col">Control Section</th>
                  </tr>
                </thead>
                <tbody>



                  @foreach($sliders as $info)
                  <tr>
                    <td>{{$info->id}}</td>
                    <td>
                      <span class="badge badge-dot mr-4">
                        @if($info->status == 'Deactive')
                        <i class="bg-warning"></i> Deactive
                        @elseif($info->status == 'Active')
                        <i class="bg-success"></i> Active
                        @endif
                      </span>
                    </td>
                    <td>
                        <a type="link" class="btn btn-success btn-sm" href="/sliders/<?php echo $info->id; ?>">View</a>
                        <a type="link" class="btn btn-default btn-sm" href="/sliders/<?php echo $info->id;?>/edit">Edit</a>
                        <form action="{{ route('sliders.destroy', $info->id) }}" method="post" style="display:inline">
                                  {{ method_field('DELETE') }}
                                  {{ csrf_field() }}
                          <input type="submit" class="btn btn-danger btn-sm" placeholder="Delete" value="Delete"/>
                        </form>
                    </td>
                  </tr>


                  @endforeach

                </tbody>
              </table>
            </div>

          </div>
        </div>
      </div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'<?php echo $color; ?>'
@endsection
@endif

resources/views/slider/show.blade.php
@extends('layouts.app')
@section('content')
<div class="card" class="col-md-12">
  <?php
  $slider = \App\Slider::find($id);
  ?>
  <div class="card-header border-0 bg-secondary">
    <h3 class="mb-0">Slider</h3>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-md-6">
        <p><b>Status</b></p>
        <p><b>Uploaded By</b></p>
      </div>
      <div class="col-md-6">
        <p class="card-text">
          {{$slider->status}}
          <?php
          $uploader = \App\User::find($slider->uploaderID);
          ?>
        </p>
        <p>{{$uploader->name}}</p>
      </div>
    </div>
    <p class="card-text" id="desc">
      <b>Description:</b><br>
    <?php
    $contentUrl = "/slider/"."/".$slider->content;
    $content = Storage::get($contentUrl);
    ?>
    {!!html_entity_decode($content)!!}
    </p>
  </div>
</div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'danger'
@endsection
@endif