routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/applicationForm/{id}', 'ApplicantController@apply');
Route::get('/viewJob/{id}', 'CareerController@viewJob');
Route::get('/viewAllJobs', function () {
    return view('viewAllJobs');
});
Route::get('/', function () {
  $message = "Welcome to OnSets!";
    return view('welcome', compact('message'));
});
Route::resource('/queries', 'QueryController');
Route::resource('/subcribeEmails', 'SubscribeController');
Route::get('/differnt/{status}', 'QueryController@DifferentQuery');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/ourinfo', 'HomeController@ourinfo');
Route::get('/viewAllStories', 'HomeController@viewAllStories');
Route::post('/ourinfoAdd', 'HomeController@ourinfoAdd');
Route::post('/ourinfoUpdate/{id}', 'HomeController@ourinfoUpdate');
Route::get('/viewApplicants/{id}', 'ApplicantController@viewApplicants');
Route::resource('/addresses', 'AddressController');
Route::resource('/products', 'ProductController');
Route::resource('/projects', 'ProjectController');
Route::resource('/careers', 'CareerController');
Route::resource('/stories', 'StoryController');
Route::resource('/roles', 'RoleController');
Route::resource('/applicants', 'ApplicantController');
Route::resource('/users', 'userController');
Route::resource('/contacts', 'ContactController');


Route::post('/usersContact', 'userController@infoAddContact');
Route::post('/usersAddress', 'userController@infoAddAddress');
Route::post('/usersContactD/{id}/{contact}', 'userController@infoDeleteContact');
Route::post('/usersAddressD/{id}/{address}', 'userController@infoDeleteAddress');
Route::get('/userContact/{id}', 'userController@AddContactView');
Route::get('/userAddress/{id}', 'userController@AddAddressView');
Route::get('/ContactEdit/{id}/{contact}', 'userController@EditContactView');
Route::get('/AddressEdit/{id}/{address}', 'userController@EditAddressView');
Route::post('/UpdateContact/{id}', 'userController@UpdateContact');
Route::post('/updateAddress/{id}', 'userController@updateAddress');


Route::resource('/media', 'MediaController');
Route::resource('/sliders', 'SliderController');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

app/Story.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Story extends Model
{
    //
      protected $table = 'stories';
}

app/Http/Controllers/StoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Story;
use Auth;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Redirect;
use File;
use Intervention\Image\ImageManagerStatic as Image;

class StoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct()
     {
         $this->middleware('auth');
     }

    public function index()
    {
      return view('story.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
          return view('story.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $story=new Story;
      $story->uploaderID    =Auth::id();
      $story->publishTitle   =$request->name;
      $story->publishDate   =$request->publishDate;
      $story->visibleFront  =$request->frontVisible;
      $story->status        =$request->status;
      $description          =$request->editor1;

      $destinationImages='story/images';
      $allowedImagefileExtension=['jpg','png','jpeg'];
      $destinationVideo='story/videos';
      $allowedVideofileExtension=['mp4','flv','m4p','mpg','mpeg','webm','mov'];

      if($request->hasFile('image')){
        $file=Input::file("image");
        $extension = $file->getClientOriginalExtension();
        $checkImage=in_array($extension,$allowedImagefileExtension);
        $filename = time() . '-' .$file->getClientOriginalName();
        if($checkImage){
          $image = Image::make($file);
          $image->resize(500, 500);
          $url = $destinationImages.'/'.$filename;
          if (!file_exists($destinationImages)) {
            mkdir($destinationImages, 666, true);
          }
          $image->save($url);
          $story->publishImage = $filename;
        }
        else{
          $message = "Only JPEG, JPG, PNG formats allowed for images!";
          return view("story.create", compact('message', 'title', 'status', 'url', 'description'));
        }
      }
      $storyDescriptionFile = time();
      $storyDescriptionUrl = "/story/".$storyDescriptionFile.".txt";
      Storage::put($storyDescriptionUrl, $description);
      $story->descriptionPath = $storyDescriptionFile.".txt";
      $story->save();

      if($request->hasFile('images')){
        $files=Input::file("images");
        foreach ($files as $key => $file) {
          $extension = $file->getClientOriginalExtension();
          $checkImage=in_array($extension,$allowedImagefileExtension);
          $filename = time() . '-' .$file->getClientOriginalName();
          if($checkImage){
            $image = Image::make($file);
            $image->resize(500, 500);
            $media = new \App\Media;
            $url = $destinationImages.'/'.$filename;
            if (!file_exists($destinationImages)) {
              mkdir($destinationImages, 666, true);
            }
            $image->save($url);
            $media->name = $filename;
            $media->type = "image";
            $media->for = "story";
            $media->forId = $story->id;
            $media->status = "Active";

            $media->save();
          }
          else{
            $message = "Only JPEG, JPG, PNG formats allowed for images!";
            $color = "danger";
            return view("story.create", compact('message', 'title', 'status', 'url', 'description', 'color'));
          }
        }
      }

      if($request->hasFile('videos')){
        $files=Input::file("videos");
        foreach ($files as $key => $file) {
          $extension = $file->getClientOriginalExtension();
          $checkVideo=in_array($extension,$allowedVideofileExtension);
          $filename = time() . '-' .$file->getClientOriginalName();
          if($checkVideo){
            $media = new \App\Media;
            $file->move($destinationVideo,$filename);
            $media->name = $filename;
            $media->type = "video";
            $media->for = "story";
            $media->forId = $story->id;
            $media->status = "Active";
            
            $media->save();
          }
          else{
            $message = "Only MP4, M4P, MOV, WEBM, MPEG, FLV formats allowed for videos!";
            $color = "danger";
            return view("story.create", compact('message', 'title', 'status', 'url', 'description', 'color'));
          }
        }
      }

        $message = "Story Saved";
        $color='success';
        return view('story.index', compact('message','color'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $story = Story::find($id);
      return view('story.show', compact('story'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      return view('story.edit', compact('id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $story = Story::find($id);
        $story->uploaderID    =Auth::id();
        $story->publishTitle   =$request->name;
        $story->publishDate   =$request->publishDate;
        $story->visibleFront  =$request->frontVisible;
        $story->status        =$request->status;
        $description          =$request->editor1;
        $destinationImages='story/images';
        $allowedImagefileExtension=['jpg','png','jpeg'];
        $destinationVideo='story/videos';
        $allowedVideofileExtension=['mp4','flv','m4p','mpg','mpeg','webm','mov'];

        if($request->hasFile('image')){
          $file=Input::file("image");
          $extension = $file->getClientOriginalExtension();
          $checkImage=in_array($extension,$allowedImagefileExtension);
          $filename = time() . '-' .$file->getClientOriginalName();
          if($checkImage){
            $image = Image::make($file);
            $image->resize(500, 500);
            $path = 'story/images/'.$story->publishImage;
            File::delete($path);
            $url = $destinationImages.'/'.$filename;
            $image->save($url);
            $story->publishImage = $filename;
          }
          else{
            $message = "Only JPEG, JPG, PNG formats allowed for images!";
            return view("story.create", compact('message', 'title', 'status', 'url', 'description'));
          }
        }

        if($request->hasFile('images')){
          $files=Input::file("images");
          foreach ($files as $key => $file) {

            $extension = $file->getClientOriginalExtension();
            $checkImage=in_array($extension,$allowedImagefileExtension);
            $filename = time() . '-' .$file->getClientOriginalName();
            if($checkImage){
              $image = Image::make($file);
              $image->resize(500, 500);
              $media = new \App\Media;
              $url = $destinationImages.'/'.$filename;
              $image->save($url);
              $media->name = $filename;
              $media->type = "image";
              $media->for = "story";
              $media->forId = $story->id;
              $media->status = "Active";
              $media->save();
              $color = "success";
            }
            else{
              $color = "danger";
              $message = "Only JPEG, JPG, PNG formats allowed for images!";
              return view("story.edit", compact('message', 'title', 'status', 'url', 'description', 'color'));
            }
          }
        }
        if($request->hasFile('videos')){
          $files=Input::file("videos");
          foreach ($files as $key => $file) {
            $extension = $file->getClientOriginalExtension();
            $checkVideo=in_array($extension,$allowedVideofileExtension);
            $filename = time() . '-' .$file->getClientOriginalName();
            if($checkVideo){
              $media = new \App\Media;
              $file->move($destinationVideo,$filename);
              $url = $destinationVideo.'/'.$filename;
              $media->name = $filename;
              $media->type = "video";
              $media->for = "story";
              $media->forId = $story->id;
              $media->status = "Active";
              $media->save();
              $color = "success";
            }
            else{
              $color = "danger";
              $message = "Only MP4, M4P, MOV, WEBM, MPEG, FLV formats allowed for videos!";
              return view("story.edit", compact('message', 'title', 'status', 'url', 'description', 'color'));
            }
          }
        }

        $descriptionFile=$story->descriptionPath;
        Storage::delete('story/'.$descriptionFile);

        $storyDescriptionFile = time();
        $storyDescriptionUrl = "/story/".$storyDescriptionFile.".txt";
        Storage::put($storyDescriptionUrl, $description);
        $story->descriptionPath = $storyDescriptionFile.".txt";

        if($story->save()){
          $message = "Story Update";
          $color='success';
          return view('story.index', compact('message','color'));
        }
        else{
          $message = "Story not Update";
          $color='danger';
          return view('story.index', compact('message','color'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

resources/views/story/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
        <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
        </div>
        <div class="col-md-12">
          <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">Story</h3>
                </div>
              </div>
            </div>
            <div class="card-body">
              <form action="/stories" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div>
                  <div class="row">
                      <div class="col-md-12">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Publish Title</label>
                        <input required type="text" id="input-postal-code" name="name" class="form-control form-control-alternative" placeholder="Title">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Publish Date</label>
                        <div class="input-group input-group-alternative">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="ni ni-calendar-grid-58"></i></span>
                            </div>
                            <input class="form-control datepicker" name="publishDate" placeholder="Select date" type="text" required>
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Status</label>
                        <select required name="status" class="form-control form-control-alternative">
                          <option value="Active">Active</option>
                          <option value="Deactive">Deactive</option>
                        </select>
                      </div>
                    </div>

                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Visible Front</label>
                        <select required name="frontVisible" class="form-control form-control-alternative">
                          <option value="1">Visble</option>
                          <option value="0">Invible</option>
                        </select>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Primary Image <small>(Only PNG, JPG, JPEG formats allowed)</small></label>
                        <label class="btn btn-success" for="image"><i class="fas fa-upload"></i> Upload Image</label><small id="imageLabel"></small>
                        <input required type="file" id="image" style="position:absolute; opacity:0; z-index:-1" name="image" class="form-control form-control-alternative" accept=".jpg,.jpeg,.png">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Images <small>(Only PNG, JPG, JPEG formats allowed)</small></label><br>
                        <label class="btn btn-success" for="images"><i class="fas fa-upload"></i> Upload Images</label><small id="imagesLabel"></small>
                        <input type="file" id="images" style="position:absolute; opacity:0; z-index:-1" name="images[]" class="form-control form-control-alternative" accept=".jpg,.jpeg,.png" multiple>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Videos <small>(Only FLV, MP4, M4P, MPEG, MOV formats allowed)</small></label>
                        <label class="btn btn-success" for="videos"><i class="fas fa-upload"></i> Upload Videos</label><small id="videosLabel"></small>
                        <input type="file" id="videos" style="position:absolute; opacity:0; z-index:-1" name="videos[]" class="form-control form-control-alternative" accept=".mp4,.m4p,.mpeg,.webm,.mov,.mpg,.flv" multiple>
                      </div>
                    </div>
                       <div class="col-md-12">
                           <div class="form-group">
                             <label class="form-control-label" for="input-username">Story Description</label>
                             <textarea class="form-control" rows="5" name="editor1" placeholder="Description"></textarea>
                           </div>
                         </div>
                    </div>
                </div>
                <!-- Save Button -->
                <div class="row">
                  <div class="col-12 text-right">
                    <input class="btn btn-default" type="submit" value="Save"></input>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'danger'
@endsection
@endif

resources/views/story/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
        <div class="col-md-12">
          <div class="card bg-secondary shadow">
            <?php
            $story = \App\Story::find($id);
            ?>
            <img class="card-img-top" src="{{asset('story/images/').'/'.$story->publishImage}}" height="500em" alt="Card image cap">
            <?php
            $media = \App\Media::where('for', 'story')->where('forId', $story->id)->get();
            ?>
            <div class="card-body">
              @if(!$media->isEmpty())
              <div class="row text-center mt-4">
                @foreach($media as $value)
                @if($value->type == 'image')
                <div class="col-md-3">
                  <img class="img img-responsive col-md-12" src="{{asset('story/images/').'/'.$value->name}}">
                  <form action="{{ route('media.destroy', $value->id) }}" method="post" style="display:inline">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <input hidden value="{{$story->id}}" name="forId">
                            <input hidden value="story" name="type">
                    <input type="submit" class="btn btn-danger btn-sm mt-2 mb-2" placeholder="Delete" value="Delete"/>
                  </form>
                </div>
                @elseif($value->type == 'video')
                <div class="col-md-3">
                  <video class="video col-md-12 mb-4" controls>
                    <source src="{{asset('story/videos/').'/'.$value->name}}">
                  </video>
                  <form action="{{ route('media.destroy', $value->id, $story->id, 'story') }}" method="post" style="display:inline">
                    <input hidden value="{{$story->id}}" name="forId">
                    <input hidden value="story" name="type">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                    <input type="submit" class="btn btn-danger btn-sm mt-2 mb-2" placeholder="Delete" value="Delete"/>
                  </form>
                </div>
                @endif
                @endforeach
              </div>
              @endif
              <form action="/stories/<?php echo $story->id;?>" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{method_field('PUT')}}
                <input type="hidden" value="{{ $story->id}}" name="id">
                <div>
                  <div class="row">
                      <div class="col-lg-12">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Publish Title</label>
                        <input type="text" required id="input-postal-code" name="name" class="form-control form-control-alternative"  value="{{ $story->publishTitle }}">
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Publish Date</label>
                        <div class="input-group input-group-alternative">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="ni ni-calendar-grid-58"></i></span>
                            </div>
                            <input class="form-control datepicker" name="publishDate" placeholder="Select date" type="text" value="{{$story->publishDate}}">
                        </div>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Status</label>
                        <select required name="status" class="form-control form-control-alternative">
                          @if($story->status=='Active')
                          <option value="Active" selected>Active</option>
                          <option value="Deactive">Deactive</option>
                          @elseif($story->status=='Deactive')
                          <option value="Active">Active</option>
                          <option value="Deactive" selected>Deactive</option>
                          @endif
                        </select>
                      </div>
                    </div>
                    <div class="col-md-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-country">Visible Front</label>
                        <select required name="frontVisible" class="form-control form-control-alternative">
                          @if($story->visibleFront=='1')
                          <option value="1" selected>Visble</option>
                          <option value="0">Invisble</option>
                          @elseif($story->visibleFront=='0')
                          <option value="1">Visble</option>
                          <option value="0" selected>Invisble</option>
                          @endif
                        </select>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Primary Image <small>(Only PNG, JPG, JPEG formats allowed)</small></label>
                        <label class="btn btn-success" for="image"><i class="fas fa-upload"></i> Upload Image</label><small id="imageLabel"></small>
                        <input type="file" id="image" style="position:absolute; opacity:0; z-index:-1" name="image" class="form-control form-control-alternative" accept=".jpg,.jpeg,.png">
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Images <small>(Only PNG, JPG, JPEG formats allowed)</small></label><br>
                        <label class="btn btn-success" for="images"><i class="fas fa-upload"></i> Upload Images</label><small id="imagesLabel"></small>
                        <input type="file" id="images" style="position:absolute; opacity:0; z-index:-1" name="images[]" class="form-control form-control-alternative" accept=".jpg,.jpeg,.png" multiple>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Videos <small>(Only FLV, MP4, M4P, MPEG, MOV formats allowed)</small></label>
                        <label class="btn btn-success" for="videos"><i class="fas fa-upload"></i> Upload Videos</label><small id="videosLabel"></small>
                        <input type="file" id="videos" style="position:absolute; opacity:0; z-index:-1" name="videos[]" class="form-control form-control-alternative" accept=".mp4,.m4p,.mpeg,.webm,.mov,.mpg,.flv" multiple>
                      </div>
                    </div>
                       <div class="col-md-12">
                           <div class="form-group">
                             <?php
                             $descriptionUrl = "/story/"."/".$story->descriptionPath;
                             $description = Storage::get($descriptionUrl);
                             ?>

                             <label class="form-control-label" for="input-username" >Story Description</label>
                             <textarea class="form-control" rows="5" name="editor1" value="{{$story->descriptionPath}}" required>{!!html_entity_decode($description)!!}</textarea>
                           </div>
                         </div>


                    </div>
                </div>
                <!-- Save Button -->
                <div class="row">
                  <div class="col-md-12 text-right">
                    <input class="btn btn-default" type="submit" value="Update"></input>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'danger'
@endsection
@endif

resources/views/story/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
        <div class="col">
          <div class="card shadow">
            <div class="card-header border-0">
              <h3 class="mb-0">Story
                <div style="display: inline; float: right" >
                  <a type="link" class="btn btn-sm btn-primary pull-right" href="{{URL::asset('stories/create')}}">Add Story</a>
                </div>
              </h3>
            </div>
            <?php
            $stories = \App\Story::all()->sortByDesc("id");
            ?>
            <div class="table-responsive">
              <table class="table align-items-center table-flush">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Status</th>
                    <th scope="col">Control Section</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($stories as $info)
                  <tr>
                    <td>{{$info->id}}</td>
                    <th scope="row">
                      <div class="media align-items-center">
                        <a href="#" class="avatar rounded-circle mr-3">
                          <img src="{{asset('story/images/').'/'.$info->publishImage}}" alt="Story Image" />
                        </a>
                        <div class="media-body">
                          <span class="mb-0 text-sm">{{$info->publishTitle}}</span>
                        </div>
                      </div>
                    </th>
                    <td>
                      <span class="badge badge-dot mr-4">
                        @if($info->status == 'Deactive')
                        <i class="bg-warning"></i> Deactive
                        @elseif($info->status == 'Active')
                        <i class="bg-success"></i> Active
                        @endif
                      </span>
                    </td>
                    <td>
                        <a type="link" class="btn btn-success btn-sm" href="/stories/<?php echo $info->id; ?>">View</a>
                        <a type="link" class="btn btn-default btn-sm" href="/stories/<?php echo $info->id;?>/edit">Edit</a>
                        <form action="{{ route('stories.destroy', $info->id) }}" method="post" style="display:inline">
                                  {{ method_field('DELETE') }}
                                  {{ csrf_field() }}
                          <input type="submit" class="btn btn-danger btn-sm" placeholder="Delete" value="Delete"/>
                        </form>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>

          </div>
        </div>
      </div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'<?php echo $color; ?>'
@endsection
@endif

resources/views/story/show.blade.php
@extends('layouts.app')

@section('content')
<div class="card" class="col-md-12">
  <img class="card-img-top" src="{{asset('story/images/').'/'.$story->publishImage}}" height="500em" alt="story Image">
  <div class="card-body">
    <?php
    if ($story->visibleFront =='1') {  $visbleStatus="Visible";}
    else{ $visbleStatus  ="Invisible"; }
     ?>

    <h2 class="card-title">{{$story->publishTitle}} <small>({{$story->status }}/{{ $visbleStatus }})</small>
      <?php
      $uploader = \App\User::find($story->uploaderID);
      ?>
      <div style="display:inline; float: right">
      <small><b>Uploaded Info:</b> {{ $uploader->name }} ({{ $story->publishDate}})</small></div>
    </h2>
    <p class="card-text" id="desc">
    <?php
    $descriptionUrl = "/story/"."/".$story->descriptionPath;
    $description = Storage::get($descriptionUrl);
    ?>
    {!!html_entity_decode($description)!!}
    </p>

  </div>
</div>
@endsection
@if(!empty($message))
@section('icon')
'ti-user'
@endsection
@section('message')
"<?php echo $message;?>"
@endsection
@section('barcolor')
'danger'
@endsection
@endif